// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKdJiQ9o37oINSAHqbfaguloXDOIamIA',
    appId: '1:276702401950:web:4ad1d0d73e906721ba328f',
    messagingSenderId: '276702401950',
    projectId: 'mojawypozyczalnia',
    authDomain: 'mojawypozyczalnia.firebaseapp.com',
    storageBucket: 'mojawypozyczalnia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWQuph_wZqYyMNKl_HnCD_lcugW76wVM',
    appId: '1:276702401950:android:a2cc944a683fbebcba328f',
    messagingSenderId: '276702401950',
    projectId: 'mojawypozyczalnia',
    storageBucket: 'mojawypozyczalnia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1v0OUuDOVhRs6aDSj-2h2GtoA0oObiY',
    appId: '1:276702401950:ios:00bc85dda11be2abba328f',
    messagingSenderId: '276702401950',
    projectId: 'mojawypozyczalnia',
    storageBucket: 'mojawypozyczalnia.firebasestorage.app',
    iosBundleId: 'com.example.licencjat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW1v0OUuDOVhRs6aDSj-2h2GtoA0oObiY',
    appId: '1:276702401950:ios:00bc85dda11be2abba328f',
    messagingSenderId: '276702401950',
    projectId: 'mojawypozyczalnia',
    storageBucket: 'mojawypozyczalnia.firebasestorage.app',
    iosBundleId: 'com.example.licencjat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcKdJiQ9o37oINSAHqbfaguloXDOIamIA',
    appId: '1:276702401950:web:7fddfda26aae9914ba328f',
    messagingSenderId: '276702401950',
    projectId: 'mojawypozyczalnia',
    authDomain: 'mojawypozyczalnia.firebaseapp.com',
    storageBucket: 'mojawypozyczalnia.firebasestorage.app',
  );
}
